export const DAMAGE_TYPES = {
    BLOCK_EXPLOSION: "Damage caused by being in the area when a block explodes.",
    CONTACT: "Damage caused when an entity contacts a block such as a Cactus, Dripstone (Stalagmite) or Berry Bush.",
    CRAMMING: "Damage caused when an entity is colliding with too many entities due to the maxEntityCramming game rule.",
    CUSTOM: "Custom damage.",
    DRAGON_BREATH: "Damage caused by a dragon breathing fire.",
    DROWNING: "Damage caused by running out of air while in water",
    DRYOUT: "Damage caused when an entity that should be in water is not.",
    ENTITY_ATTACK: "Damage caused when an entity attacks another entity.",
    ENTITY_EXPLOSION: "Damage caused by being in the area when an entity, such as a Creeper, explodes.",
    ENTITY_SWEEP_ATTACK: "Damage caused when an entity attacks another entity in a sweep attack.",
    FALL: "Damage caused when an entity falls a distance greater than 3 blocks",
    FALLING_BLOCK: "Damage caused by being hit by a falling block which deals damage",
    FIRE: "Damage caused by direct exposure to fire",
    FIRE_TICK: "Damage caused due to burns caused by fire",
    FLY_INTO_WALL: "Damage caused when an entity runs into a wall.",
    FREEZE: "Damage caused from freezing.",
    HOT_FLOOR: "Damage caused when an entity steps on Material.MAGMA_BLOCK.",
    KILL: "Damage caused by /kill command",
    LAVA: "Damage caused by direct exposure to lava",
    LIGHTNING: "Damage caused by being struck by lightning",
    MAGIC: "Damage caused by being hit by a damage potion or spell",
    MELTING: "Damage caused due to a snowman melting",
    POISON: "Damage caused due to an ongoing poison effect",
    PROJECTILE: "Damage caused when attacked by a projectile.",
    SONIC_BOOM: "Damage caused by the Sonic Boom attack from Warden",
    STARVATION: "Damage caused by starving due to having an empty hunger bar",
    SUFFOCATION: "Damage caused by being put in a block",
    SUICIDE: "Damage caused by committing suicide.",
    THORNS: "Damage caused in retaliation to another attack by the Thorns enchantment.",
    VOID: "Damage caused by falling into the void",
    WITHER: "Damage caused by Wither potion effect",
    WORLD_BORDER: "Damage caused by the World Border",
};
